// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Server.Models;

#nullable disable

namespace app.Server.Migrations
{
    [DbContext(typeof(EcodbContext))]
    [Migration("20240527082457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app.Server.Models.Acceptance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("HazardousWasteId")
                        .HasColumnType("int")
                        .HasColumnName("hazardous_waste_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("HazardousWasteId");

                    b.HasIndex("TransactionId");

                    b.ToTable("acceptance", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Bonuses")
                        .HasColumnType("int")
                        .HasColumnName("bonuses");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_start");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int")
                        .HasColumnName("partner_id");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("terms");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("PartnerId");

                    b.ToTable("discounts", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.HazardClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("hazard_class", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.HazardousWaste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Bonuses")
                        .HasColumnType("int")
                        .HasColumnName("bonuses");

                    b.Property<int>("HazardClassId")
                        .HasColumnType("int")
                        .HasColumnName("hazard_class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("HazardClassId");

                    b.ToTable("hazardous_waste", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.ReceivingDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("discount_id");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("DiscountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("receiving_discounts", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BonusesEnd")
                        .HasColumnType("int")
                        .HasColumnName("bonuses_end");

                    b.Property<int>("BonusesStart")
                        .HasColumnType("int")
                        .HasColumnName("bonuses_start");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("transaction_types", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Bonuses")
                        .HasColumnType("int")
                        .HasColumnName("bonuses");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_hash");

                    b.Property<string>("Encrypt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypt");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("app.Server.Models.Acceptance", b =>
                {
                    b.HasOne("app.Server.Models.HazardousWaste", "HazardousWaste")
                        .WithMany("Acceptances")
                        .HasForeignKey("HazardousWasteId")
                        .IsRequired()
                        .HasConstraintName("acceptance_hazardous_waste_id_fk");

                    b.HasOne("app.Server.Models.Transaction", "Transaction")
                        .WithMany("Acceptances")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("acceptance_transaction_id_fk");

                    b.Navigation("HazardousWaste");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("app.Server.Models.Discount", b =>
                {
                    b.HasOne("app.Server.Models.Partner", "Partner")
                        .WithMany("Discounts")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("discounts_partner_id_fk");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("app.Server.Models.HazardousWaste", b =>
                {
                    b.HasOne("app.Server.Models.HazardClass", "HazardClass")
                        .WithMany("HazardousWastes")
                        .HasForeignKey("HazardClassId")
                        .IsRequired()
                        .HasConstraintName("hazardous_waste_hazard_class_id_fk");

                    b.Navigation("HazardClass");
                });

            modelBuilder.Entity("app.Server.Models.ReceivingDiscount", b =>
                {
                    b.HasOne("app.Server.Models.Discount", "Discount")
                        .WithMany("ReceivingDiscounts")
                        .HasForeignKey("DiscountId")
                        .IsRequired()
                        .HasConstraintName("receiving_discounts_discount_id_fk");

                    b.HasOne("app.Server.Models.Transaction", "Transaction")
                        .WithMany("ReceivingDiscounts")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("receiving_discounts_transaction_id_fk");

                    b.Navigation("Discount");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("app.Server.Models.Transaction", b =>
                {
                    b.HasOne("app.Server.Models.TransactionType", "Type")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("transactions_type_id_fk");

                    b.HasOne("app.Server.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("transactions_user_id_fk");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("app.Server.Models.User", b =>
                {
                    b.HasOne("app.Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fk");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("app.Server.Models.Discount", b =>
                {
                    b.Navigation("ReceivingDiscounts");
                });

            modelBuilder.Entity("app.Server.Models.HazardClass", b =>
                {
                    b.Navigation("HazardousWastes");
                });

            modelBuilder.Entity("app.Server.Models.HazardousWaste", b =>
                {
                    b.Navigation("Acceptances");
                });

            modelBuilder.Entity("app.Server.Models.Partner", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("app.Server.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("app.Server.Models.Transaction", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("ReceivingDiscounts");
                });

            modelBuilder.Entity("app.Server.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("app.Server.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
